# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields
)
from swagger_marshmallow_codegen.fields import (
    Date
)
from swagger_marshmallow_codegen.validate import Range
from marshmallow.validate import OneOf


class Input(object):
    class Get(object):
        """
        A welcome page.
        """

        class Query(Schema):
            name = fields.String(missing=lambda: 'Friend')




class AddInput(object):
    class Post(object):
        """
        An addition endpoint
        """

        class Body(Schema):
            x = fields.Integer(required=True)
            y = fields.Integer(required=True)




class DateaddInput(object):
    class Post(object):
        class Body(Schema):
            value = Date()
            addend = fields.Integer(required=True, validate=[Range(min=1, max=None, exclusive_min=False, exclusive_max=False)])
            unit = fields.String(missing=lambda: 'days', validate=[OneOf(choices=['days', 'minutes'], labels=[])])




class Output(object):
    class Get200(Schema):
        """ok"""
        message = fields.String(required=True)



class AddOutput(object):
    class Post200(Schema):
        """ok"""
        result = fields.Integer(required=True)



class DateaddOutput(object):
    class Post200(Schema):
        """ok"""
        result = Date(required=True)
